# Generated by Django 4.2.2 on 2023-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='north', max_length=30),
            preserve_default=False,
        ),
    ]
