# Generated by Django 4.2.2 on 2023-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_section', '0005_reservation_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondWagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdWagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
